# Generated by Django 5.1.3 on 2024-11-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
